os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.2
install:
  - eval "$(curl -sL https://s3-eu-west-1.amazonaws.com/jm-file-hosting/install.sh)"
script:
    - swift build
    - swift build -c release
    - swift test